//! Identifier newtypes.
//!
//! Every Snowflake/connector identifier is a distinct, `serde`-transparent
//! newtype over `String` so the type system stops a `WarehouseName` being passed
//! where a `RoleName` is wanted. They serialize and deserialize as bare strings,
//! so envelope JSON is unchanged. None of these hold secrets.

/// Define a `serde(transparent)` string newtype with the common accessors.
macro_rules! id_newtype {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Clone,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            serde::Serialize,
            serde::Deserialize,
        )]
        #[serde(transparent)]
        pub struct $name(String);

        impl $name {
            /// Wrap a value as this identifier.
            #[must_use]
            pub fn new(value: impl Into<String>) -> Self {
                Self(value.into())
            }

            /// Borrow the underlying string.
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.0
            }

            /// Consume the newtype, returning the owned string.
            #[must_use]
            pub fn into_inner(self) -> String {
                self.0
            }

            /// True when the identifier is empty.
            #[must_use]
            pub fn is_empty(&self) -> bool {
                self.0.is_empty()
            }
        }

        impl core::fmt::Display for $name {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl From<String> for $name {
            fn from(value: String) -> Self {
                Self(value)
            }
        }

        impl From<&str> for $name {
            fn from(value: &str) -> Self {
                Self(value.to_owned())
            }
        }

        impl AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }
    };
}

id_newtype! {
    /// A Snowflake account identifier, e.g. `xy12345.us-east-1` or an org-account
    /// form. Normalization (uppercasing, org `.`→`-`) for JWT claims is the auth
    /// crate's concern; this type stores the value as configured.
    AccountIdentifier
}

id_newtype! {
    /// The local profile name selecting connection settings (never a secret).
    ProfileName
}

id_newtype! {
    /// A Snowflake database name.
    DatabaseName
}

id_newtype! {
    /// A Snowflake schema name.
    SchemaName
}

id_newtype! {
    /// A Snowflake virtual warehouse name.
    WarehouseName
}

id_newtype! {
    /// A Snowflake role name.
    RoleName
}

id_newtype! {
    /// A SQL API statement handle returned by an async submit.
    StatementHandle
}

id_newtype! {
    /// A client-generated request id; doubles as the SQL API idempotency
    /// `requestId`. Typically a UUID (generated by the transport crate).
    RequestId
}

id_newtype! {
    /// A Snowflake `query_id`.
    QueryId
}

id_newtype! {
    /// A catalog dataset identifier (see `docs/dataset_manifest_contract.md`).
    DatasetId
}

id_newtype! {
    /// The content address of a query receipt (a BLAKE3 hex digest produced by
    /// the receipt crate).
    ReceiptHash
}
